# Generated by Django 2.2 on 2021-07-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hirehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=200)),
                ('place', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.CharField(blank=True, max_length=15, null=True)),
                ('per_meter', models.CharField(blank=True, max_length=15, null=True)),
                ('size', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=200)),
                ('place', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('per_meter', models.FloatField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='newhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=200)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('per_meter', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
