# Generated by Django 2.2 on 2021-07-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
